import { Platform, StatusBar } from 'react-native';

export const getStyles = theme => {
  return {
    container: {
      flex: 1,
      backgroundColor: theme.background,
      paddingTop: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight,
      paddingHorizontal: 16,
    },
    content: { flex: 1 },
    list: { marginTop: 10 },
    sectionHeader: {
      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection: 'row',
      marginVertical: 10,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.textPrimary,
    },
    topSection: { marginBottom: 15 },

    dateCard: {
      width: 45,
      height: 75,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 12,
      //backgroundColor: theme.dateCard,
      marginRight: 10,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    activeDateCard: {
      backgroundColor: theme.primary,
      borderColor: theme.blackSecondary,
    },
    dateNumber: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.dayTextColor,
    },
    dateDay: {
      fontSize: 9,
      color: theme.textMuted,
      marginTop: 6,
      marginBottom: 4,
      textAlign: 'center',
    },
    dateMonthName: {
      fontSize: 9,
      fontWeight: 'bold',
      color: theme.textMuted,
      marginTop: 1,
    },
    activeDateText: {
      color: theme.surface,
    },
    chartContainer: {
      alignItems: 'center',
      marginTop: 20,
      backgroundColor: theme.background,
      padding: 15,
      width: '100%',
    },
    dotContainer: {
      justifyContent: 'space-evenly',
      flexDirection: 'row',
      width: '107%',
      marginTop: 20,
    },
    chartItem: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    centerChartCount: {
      fontSize: 24,
      color: theme.primary,
      fontWeight: '600',
    },
    centerChartLabel: {
      fontSize: 12,
      color: theme.primary,
      fontWeight: '600',
    },
    dotText: {
      fontSize: 11,
      color: theme.textChartLabel,
      fontWeight: '600',
    },
    dot: {
      width: 6.5,
      height: 6.5,
      borderRadius: 4,
      marginRight: 8,
      marginLeft: 8,
    },
    taskCard: {
      backgroundColor: theme.background,
      borderRadius: 20,
      padding: 16,
      borderTopColor: theme.taskDefaultBg,
      borderTopWidth: 1.8,
    },
    cardTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    cardBottomRow: {
      marginTop: -10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    taskTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.textPrimary,
      flex: 1,
    },
    actionButtons: {
      flexDirection: 'row',
      gap: 15,
    },
    leftInfoGroup: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    dateTimeText: {
      fontSize: 12,
      color: theme.textPrimary,
      fontWeight: '500',
    },
    rightActionsGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginRight: -10,
    },
    textPriorityBadge: {
      flexDirection: 'row',
      backgroundColor: theme.badgeBackground,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
      marginTop: 4,
      width: 72,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: 'bold',
      color: theme.textBadge,
      textAlign: 'center',
    },
    checkCompleted: {
      backgroundColor: theme.completedBg,
      borderColor: theme.completedBg,
    },
    completeCheckCircle: {
      borderColor: theme.borderLight,
      backgroundColor: theme.checkButton,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 16,
      height: 26,
      width: 26,
      marginTop: 5,
    },
    checkedCircle: {
      backgroundColor: theme.buttonDisabled,
      borderColor: theme.buttonDisabled,
      opacity: 0.5,
    },
    checkIcon: {
      fontSize: 14,
      fontWeight: 'bold',
    },
    iconCircle: {
      width: 26,
      height: 26,
      borderRadius: 16,
      marginRight: -10,
      backgroundColor: theme.surface,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: theme.blackPure,
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    overdueIndicator: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: 4,
      backgroundColor: theme.chartOverdue,
    },

    modalOverlay: {
      flex: 1,
      backgroundColor: theme.shadow,
      justifyContent: 'center',
      alignItems: 'center',
    },
    priorityMenu: {
      backgroundColor: theme.white,
      width: '70%',
      borderRadius: 24,
      padding: 16,
      elevation: 10,
    },
    menuTitle: {
      textAlign: 'center',
      fontWeight: 'bold',
      color: theme.textMuted,
      marginBottom: 15,
      fontSize: 15,
    },
    menuItem: {
      paddingVertical: 15,
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: theme.taskDefaultBg,
    },
    menuItemText: { fontSize: 17, fontWeight: '600' },
    deleteBox: {
      backgroundColor: theme.surface,
      width: '80%',
      borderRadius: 24,
      padding: 24,
      alignItems: 'center',
      elevation: 10,
    },
    subTitle: {
      color: theme.textMuted,
      fontSize: 14,
      marginBottom: 20,
      textAlign: 'center',
    },
    modalButtonRow: {
      flexDirection: 'row',
      width: '100%',
      gap: 12,
    },
    cancelBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.surface,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    cancelBtnText: {
      color: theme.primary,
      fontWeight: '600',
    },
    confirmBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: theme.deleteIcon,
      alignItems: 'center',
    },
    confirmBtnText: {
      color: theme.white,
      fontWeight: '600',
    },
    undoMessage: {
      position: 'absolute',
      bottom: 10,
      left: 20,
      right: 20,
      backgroundColor: theme.blackSecondary,
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 15,
      borderRadius: 12,
      elevation: 5,
      alignItems: 'center',
    },
    undoText: {
      color: theme.white,
      fontWeight: '600',
    },
    undoBtn: {
      color: theme.accent,
      fontWeight: 'bold',
    },
    todayText: {
      color: theme.accent,
      fontWeight: 'bold',
      fontSize: 14,
    },
    sectionHeaderText: {
      fontSize: 14,
      fontWeight: 'bold',
      color: theme.primary,
      letterSpacing: 1,
      textAlign: 'center',
    },
    emptyTaskContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyTaskText: {
      color: theme.textMuted,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    filterIconContainer: {
      flexDirection: 'row',
    },
  };
};
